In [184]:
# EDA
import pandas as pd
import plotly.express as px

# ML
from sklearn.datasets import load_iris
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler

# HP
import optuna

### Carga de Dados

In [185]:
iris = load_iris()

In [186]:
# Transforma iris em um DataFrame
df_iris = pd.DataFrame(iris.data, columns=iris.feature_names)

In [187]:
df_iris['target'] = iris.target

In [188]:
df_iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [189]:
df_iris.head(20)

    sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                 5.1               3.5  ...               0.2       0
1                 4.9               3.0  ...               0.2       0
2                 4.7               3.2  ...               0.2       0
3                 4.6               3.1  ...               0.2       0
4                 5.0               3.6  ...               0.2       0
5                 5.4               3.9  ...               0.4       0
6                 4.6               3.4  ...               0.3       0
7                 5.0               3.4  ...               0.2       0
8                 4.4               2.9  ...               0.2       0
9                 4.9               3.1  ...               0.1       0
10                5.4               3.7  ...               0.2       0
11                4.8               3.4  ...               0.2       0
12                4.8               3.0  ...               0.1       0
13                4.3               3.0  ...               0.1       0
14                5.8               4.0  ...               0.2       0
15                5.7               4.4  ...               0.4       0
16                5.4               3.9  ...               0.4       0
17                5.1               3.5  ...               0.3       0
18                5.7               3.8  ...               0.3       0
19                5.1               3.8  ...               0.3       0

[20 rows x 5 columns]

In [190]:
df_iris.tail(20)

     sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
130                7.4               2.8  ...               1.9       2
131                7.9               3.8  ...               2.0       2
132                6.4               2.8  ...               2.2       2
133                6.3               2.8  ...               1.5       2
134                6.1               2.6  ...               1.4       2
135                7.7               3.0  ...               2.3       2
136                6.3               3.4  ...               2.4       2
137                6.4               3.1  ...               1.8       2
138                6.0               3.0  ...               1.8       2
139                6.9               3.1  ...               2.1       2
140                6.7               3.1  ...               2.4       2
141                6.9               3.1  ...               2.3       2
142                5.8               2.7  ...               1.9       2
143                6.8               3.2  ...               2.3       2
144                6.7               3.3  ...               2.5       2
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[20 rows x 5 columns]

### EDA

In [191]:
df_iris.describe()

       sepal length (cm)  sepal width (cm)  ...  petal width (cm)      target
count         150.000000        150.000000  ...        150.000000  150.000000
mean            5.843333          3.057333  ...          1.199333    1.000000
std             0.828066          0.435866  ...          0.762238    0.819232
min             4.300000          2.000000  ...          0.100000    0.000000
25%             5.100000          2.800000  ...          0.300000    0.000000
50%             5.800000          3.000000  ...          1.300000    1.000000
75%             6.400000          3.300000  ...          1.800000    2.000000
max             7.900000          4.400000  ...          2.500000    2.000000

[8 rows x 5 columns]

In [192]:
df_iris.shape

(150, 5)

In [193]:
df_iris.target.value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [194]:
df_iris.target.value_counts(normalize=True)

target
0    0.333333
1    0.333333
2    0.333333
Name: proportion, dtype: float64

In [195]:
X = df_iris.drop('target', axis=1)
y = df_iris['target']

In [196]:
scaler = StandardScaler()
X_tranformed = scaler.fit_transform(X)

In [197]:
def gmm_objective(trial):
    n_components = trial.suggest_int('n_components', 2, 10)
    covariance_type = trial.suggest_categorical('covariance_type', ['full', 'tied', 'diag', 'spherical'])

    gmm = GaussianMixture(n_components=n_components, covariance_type=covariance_type, random_state=42)

    gmm.fit(X_tranformed)

    bic_gmm = gmm.bic(X_tranformed)

    return bic_gmm

In [198]:
search_space = {'n_components': [3, 4, 5, 6, 7, 8, 9, 10],
                'covariance_type': ['full', 'tied', 'diag', 'spherical']}

sampler = optuna.samplers.GridSampler(search_space=search_space)

estudo_gmm = optuna.create_study(direction='minimize', sampler=sampler)

[I 2026-06-06 15:02:38,338] A new study created in memory with name: no-name-64398997-4837-4908-abb7-f8dc0f462b16

In [199]:
estudo_gmm.optimize(gmm_objective, n_trials=32)

[I 2026-06-06 15:02:38,352] Trial 0 finished with value: 860.0529735540067 and parameters: {'n_components': 6, 'covariance_type': 'tied'}. Best is trial 0 with value: 860.0529735540067.
[I 2026-06-06 15:02:38,359] Trial 1 finished with value: 967.5949202389686 and parameters: {'n_components': 9, 'covariance_type': 'diag'}. Best is trial 0 with value: 860.0529735540067.
[I 2026-06-06 15:02:38,372] Trial 2 finished with value: 850.7362324512615 and parameters: {'n_components': 5, 'covariance_type': 'tied'}. Best is trial 2 with value: 850.7362324512615.
[I 2026-06-06 15:02:38,393] Trial 3 finished with value: 901.5377319262867 and parameters: {'n_components': 5, 'covariance_type': 'full'}. Best is trial 2 with value: 850.7362324512615.
[I 2026-06-06 15:02:38,397] Trial 4 finished with value: 1033.1586626992714 and parameters: {'n_components': 3, 'covariance_type': 'diag'}. Best is trial 2 with value: 850.7362324512615.
[I 2026-06-06 15:02:38,405] Trial 5 finished with value: 865.9095293704239 and parameters: {'n_components': 9, 'covariance_type': 'tied'}. Best is trial 2 with value: 850.7362324512615.
[I 2026-06-06 15:02:38,410] Trial 6 finished with value: 1110.1186332762309 and parameters: {'n_components': 7, 'covariance_type': 'spherical'}. Best is trial 2 with value: 850.7362324512615.
[I 2026-06-06 15:02:38,416] Trial 7 finished with value: 1111.7938043454863 and parameters: {'n_components': 5, 'covariance_type': 'spherical'}. Best is trial 2 with value: 850.7362324512615.
[I 2026-06-06 15:02:38,422] Trial 8 finished with value: 918.1221972673793 and parameters: {'n_components': 7, 'covariance_type': 'diag'}. Best is trial 2 with value: 850.7362324512615.
[I 2026-06-06 15:02:38,428] Trial 9 finished with value: 844.098655235557 and parameters: {'n_components': 8, 'covariance_type': 'tied'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,433] Trial 10 finished with value: 1243.7509093225394 and parameters: {'n_components': 3, 'covariance_type': 'spherical'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,458] Trial 11 finished with value: 1026.069283398017 and parameters: {'n_components': 8, 'covariance_type': 'full'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,463] Trial 12 finished with value: 960.9336228077348 and parameters: {'n_components': 4, 'covariance_type': 'diag'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,467] Trial 13 finished with value: 930.0157867621712 and parameters: {'n_components': 3, 'covariance_type': 'tied'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,471] Trial 14 finished with value: 1065.2539421937943 and parameters: {'n_components': 9, 'covariance_type': 'spherical'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,477] Trial 15 finished with value: 1143.3959446679069 and parameters: {'n_components': 4, 'covariance_type': 'spherical'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,495] Trial 16 finished with value: 992.0794195373971 and parameters: {'n_components': 10, 'covariance_type': 'diag'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,504] Trial 17 finished with value: 849.3008779426348 and parameters: {'n_components': 4, 'covariance_type': 'full'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,508] Trial 18 finished with value: 1077.7868440252132 and parameters: {'n_components': 10, 'covariance_type': 'spherical'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,528] Trial 19 finished with value: 1129.3513947073666 and parameters: {'n_components': 9, 'covariance_type': 'full'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,568] Trial 20 finished with value: 955.2591996304019 and parameters: {'n_components': 7, 'covariance_type': 'full'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,586] Trial 21 finished with value: 921.8577029229792 and parameters: {'n_components': 5, 'covariance_type': 'diag'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,592] Trial 22 finished with value: 1122.664649351754 and parameters: {'n_components': 8, 'covariance_type': 'spherical'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,596] Trial 23 finished with value: 927.962397148154 and parameters: {'n_components': 6, 'covariance_type': 'diag'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,606] Trial 24 finished with value: 867.859836626896 and parameters: {'n_components': 4, 'covariance_type': 'tied'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,641] Trial 25 finished with value: 1100.4079925713386 and parameters: {'n_components': 10, 'covariance_type': 'full'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,646] Trial 26 finished with value: 1126.68146269974 and parameters: {'n_components': 6, 'covariance_type': 'spherical'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,659] Trial 27 finished with value: 968.6085667569015 and parameters: {'n_components': 6, 'covariance_type': 'full'}. Best is trial 9 with value: 844.098655235557.
[I 2026-06-06 15:02:38,665] Trial 28 finished with value: 841.1905492967948 and parameters: {'n_components': 3, 'covariance_type': 'full'}. Best is trial 28 with value: 841.1905492967948.
[I 2026-06-06 15:02:38,672] Trial 29 finished with value: 938.7893714077384 and parameters: {'n_components': 8, 'covariance_type': 'diag'}. Best is trial 28 with value: 841.1905492967948.
[I 2026-06-06 15:02:38,683] Trial 30 finished with value: 869.1274614212463 and parameters: {'n_components': 10, 'covariance_type': 'tied'}. Best is trial 28 with value: 841.1905492967948.
[I 2026-06-06 15:02:38,693] Trial 31 finished with value: 881.1995931847041 and parameters: {'n_components': 7, 'covariance_type': 'tied'}. Best is trial 28 with value: 841.1905492967948.

In [200]:
best_params = estudo_gmm.best_params

In [201]:
best_gmm = GaussianMixture(n_components=best_params['n_components'], covariance_type=best_params['covariance_type'], random_state=42)

best_gmm.fit(X_tranformed)

best_bic = best_gmm.bic(X_tranformed)

In [202]:
print("Quantidade ideal de componentes: ", best_params['n_components'])
print("Tipo de Covariância: ", best_params['covariance_type'])
print("BIC do melhor modelo: ", best_bic)

Quantidade ideal de componentes:  3
Tipo de Covariância:  full
BIC do melhor modelo:  841.1905492967948

In [203]:
clusters_gmm = best_gmm.predict(X_tranformed)

In [204]:
clusters_gmm

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [205]:
clusters_gmm_prob = best_gmm.predict_proba(X_tranformed)

In [206]:
clusters_gmm_prob

array([[2.74503381e-011, 1.00000000e+000, 0.00000000e+000],
       [1.16033052e-007, 9.99999884e-001, 0.00000000e+000],
       [9.72921434e-009, 9.99999990e-001, 5.88168010e-278],
       [2.02193473e-007, 9.99999798e-001, 3.33173699e-141],
       [9.67775891e-012, 1.00000000e+000, 0.00000000e+000],
       [1.14329874e-012, 1.00000000e+000, 0.00000000e+000],
       [5.99406192e-009, 9.99999994e-001, 4.07722398e-049],
       [4.78561583e-010, 1.00000000e+000, 0.00000000e+000],
       [4.58916917e-007, 1.19519047e-001, 8.80480494e-001],
       [9.28895274e-008, 9.99999907e-001, 0.00000000e+000],
       [1.09664613e-012, 1.00000000e+000, 0.00000000e+000],
       [3.80456745e-009, 9.99999996e-001, 0.00000000e+000],
       [1.96191178e-007, 9.99999804e-001, 0.00000000e+000],
       [8.18276018e-008, 3.32205264e-002, 9.66779392e-001],
       [1.24741926e-016, 1.00000000e+000, 0.00000000e+000],
       [1.33001229e-018, 1.00000000e+000, 0.00000000e+000],
       [1.50274710e-014, 1.00000000e+000, 0.00000000e+000],
       [3.82289429e-011, 1.00000000e+000, 0.00000000e+000],
       [3.02844598e-012, 1.00000000e+000, 0.00000000e+000],
       [8.54641631e-013, 1.00000000e+000, 0.00000000e+000],
       [6.40382286e-009, 9.99999994e-001, 0.00000000e+000],
       [1.18716909e-011, 1.00000000e+000, 0.00000000e+000],
       [3.57341002e-010, 1.00000000e+000, 2.52968430e-114],
       [4.37213278e-007, 9.99999563e-001, 0.00000000e+000],
       [5.65731913e-007, 9.99999434e-001, 0.00000000e+000],
       [8.49752269e-007, 9.99999150e-001, 0.00000000e+000],
       [5.93788174e-009, 9.99999994e-001, 0.00000000e+000],
       [5.34760727e-011, 1.00000000e+000, 0.00000000e+000],
       [1.08612267e-010, 1.00000000e+000, 0.00000000e+000],
       [9.14373123e-008, 9.99999909e-001, 1.83858360e-315],
       [2.37113842e-007, 9.99999763e-001, 0.00000000e+000],
       [6.69615113e-010, 9.99999999e-001, 0.00000000e+000],
       [5.42986377e-015, 1.00000000e+000, 0.00000000e+000],
       [2.78013770e-017, 1.00000000e+000, 0.00000000e+000],
       [6.01981922e-008, 9.99999940e-001, 0.00000000e+000],
       [1.71675981e-009, 9.99999998e-001, 0.00000000e+000],
       [6.76357462e-012, 1.00000000e+000, 0.00000000e+000],
       [2.56649997e-011, 1.00000000e+000, 0.00000000e+000],
       [3.73886886e-008, 3.84205947e-002, 9.61579368e-001],
       [3.52151152e-010, 1.00000000e+000, 0.00000000e+000],
       [3.85270383e-011, 1.00000000e+000, 0.00000000e+000],
       [5.31829344e-006, 1.09578337e-003, 9.98898898e-001],
       [9.99479549e-009, 8.04127209e-002, 9.19587269e-001],
       [1.34274632e-007, 9.99999866e-001, 6.39772526e-231],
       [1.11765236e-009, 9.99999999e-001, 0.00000000e+000],
       [2.48814217e-007, 9.99999751e-001, 7.12708847e-301],
       [2.17149663e-012, 1.00000000e+000, 0.00000000e+000],
       [3.00582904e-008, 9.99999970e-001, 1.41047482e-134],
       [1.35235082e-012, 1.00000000e+000, 0.00000000e+000],
       [9.10052706e-010, 9.99999999e-001, 0.00000000e+000],
       [1.00000000e+000, 8.43405828e-100, 0.00000000e+000],
       [1.00000000e+000, 2.10741342e-087, 0.00000000e+000],
       [1.00000000e+000, 5.75881684e-112, 0.00000000e+000],
       [1.00000000e+000, 3.24968736e-065, 4.96079249e-212],
       [1.00000000e+000, 1.10724853e-097, 0.00000000e+000],
       [1.00000000e+000, 1.76011857e-080, 0.00000000e+000],
       [1.00000000e+000, 3.66011815e-097, 0.00000000e+000],
       [1.00000000e+000, 3.13150547e-033, 1.37798033e-031],
       [1.00000000e+000, 3.31776329e-092, 0.00000000e+000],
       [1.00000000e+000, 5.12917571e-060, 5.59653872e-062],
       [1.15970687e-002, 8.76980882e-044, 9.88402931e-001],
       [1.00000000e+000, 3.33090624e-074, 0.00000000e+000],
       [1.00000000e+000, 3.22627781e-064, 0.00000000e+000],
       [1.00000000e+000, 7.44734747e-094, 0.00000000e+000],
       [1.00000000e+000, 1.49104860e-047, 0.00000000e+000],
       [1.00000000e+000, 1.32075560e-084, 0.00000000e+000],
       [1.00000000e+000, 5.59571888e-084, 8.02029097e-167],
       [1.00000000e+000, 2.44927891e-060, 0.00000000e+000],
       [1.00000000e+000, 1.15545229e-097, 0.00000000e+000],
       [1.00000000e+000, 1.18658957e-055, 0.00000000e+000],
       [1.00000000e+000, 1.30455220e-107, 2.13471806e-268],
       [1.00000000e+000, 1.29232585e-064, 0.00000000e+000],
       [1.00000000e+000, 1.17330622e-112, 0.00000000e+000],
       [1.00000000e+000, 3.86615462e-090, 0.00000000e+000],
       [1.00000000e+000, 1.93535756e-077, 0.00000000e+000],
       [1.00000000e+000, 7.28819436e-085, 0.00000000e+000],
       [1.00000000e+000, 1.36137191e-107, 0.00000000e+000],
       [1.00000000e+000, 4.58750637e-122, 0.00000000e+000],
       [1.00000000e+000, 1.42012215e-087, 0.00000000e+000],
       [1.00000000e+000, 7.40056273e-041, 0.00000000e+000],
       [1.00000000e+000, 1.28250740e-052, 0.00000000e+000],
       [1.00000000e+000, 2.03064550e-047, 0.00000000e+000],
       [1.00000000e+000, 2.20934311e-057, 0.00000000e+000],
       [1.00000000e+000, 1.01046492e-119, 0.00000000e+000],
       [1.00000000e+000, 4.74300791e-083, 1.34943644e-015],
       [1.00000000e+000, 1.11063177e-085, 0.00000000e+000],
       [1.00000000e+000, 2.55779019e-100, 0.00000000e+000],
       [1.00000000e+000, 6.08542926e-088, 0.00000000e+000],
       [1.00000000e+000, 9.74107873e-063, 0.00000000e+000],
       [1.00000000e+000, 2.44676333e-063, 7.73944906e-219],
       [1.00000000e+000, 1.88250422e-074, 0.00000000e+000],
       [1.00000000e+000, 2.08797093e-088, 0.00000000e+000],
       [1.00000000e+000, 7.51175976e-062, 0.00000000e+000],
       [5.39408361e-002, 1.43796590e-035, 9.46059164e-001],
       [1.00000000e+000, 3.70752514e-069, 0.00000000e+000],
       [1.00000000e+000, 2.50337253e-064, 0.00000000e+000],
       [1.00000000e+000, 7.32055786e-068, 0.00000000e+000],
       [1.00000000e+000, 1.67331684e-075, 0.00000000e+000],
       [1.00000000e+000, 1.31737783e-028, 6.49846523e-012],
       [1.00000000e+000, 3.24459894e-065, 0.00000000e+000],
       [1.00000000e+000, 3.87080631e-206, 7.42671057e-153],
       [1.00000000e+000, 6.31331724e-130, 2.07619640e-059],
       [1.00000000e+000, 1.65615374e-191, 0.00000000e+000],
       [1.00000000e+000, 2.73176147e-153, 0.00000000e+000],
       [1.00000000e+000, 3.50323322e-183, 0.00000000e+000],
       [1.00000000e+000, 1.71544552e-244, 0.00000000e+000],
       [1.00000000e+000, 6.20973239e-093, 0.00000000e+000],
       [1.00000000e+000, 1.81507031e-209, 0.00000000e+000],
       [1.00000000e+000, 6.64885249e-175, 0.00000000e+000],
       [1.00000000e+000, 1.46633079e-216, 0.00000000e+000],
       [1.00000000e+000, 1.64394497e-134, 0.00000000e+000],
       [1.00000000e+000, 3.59559098e-145, 0.00000000e+000],
       [1.00000000e+000, 3.72985441e-165, 0.00000000e+000],
       [1.00000000e+000, 2.25016927e-131, 5.38077905e-077],
       [1.00000000e+000, 5.02607005e-156, 0.00000000e+000],
       [1.00000000e+000, 6.48380294e-159, 0.00000000e+000],
       [1.00000000e+000, 7.66186164e-149, 0.00000000e+000],
       [1.00000000e+000, 8.52639823e-244, 0.00000000e+000],
       [1.00000000e+000, 1.59860510e-283, 0.00000000e+000],
       [1.00000000e+000, 2.00475378e-117, 0.00000000e+000],
       [1.00000000e+000, 1.58958227e-184, 0.00000000e+000],
       [1.00000000e+000, 1.70364813e-123, 3.59789983e-183],
       [1.00000000e+000, 4.96228611e-253, 0.00000000e+000],
       [1.00000000e+000, 9.40660381e-121, 0.00000000e+000],
       [1.00000000e+000, 7.37469572e-171, 0.00000000e+000],
       [1.00000000e+000, 5.04465060e-184, 0.00000000e+000],
       [1.00000000e+000, 3.88285818e-114, 0.00000000e+000],
       [1.00000000e+000, 1.75428453e-115, 0.00000000e+000],
       [1.00000000e+000, 1.15042425e-168, 0.00000000e+000],
       [1.00000000e+000, 6.80664331e-169, 0.00000000e+000],
       [1.00000000e+000, 1.61698872e-203, 0.00000000e+000],
       [1.00000000e+000, 3.16648167e-218, 0.00000000e+000],
       [1.00000000e+000, 1.03088951e-173, 0.00000000e+000],
       [1.00000000e+000, 1.75115396e-118, 0.00000000e+000],
       [1.00000000e+000, 6.88308862e-142, 0.00000000e+000],
       [1.00000000e+000, 1.41409705e-222, 0.00000000e+000],
       [1.00000000e+000, 5.80181212e-177, 7.05023921e-224],
       [1.00000000e+000, 1.63666243e-146, 0.00000000e+000],
       [1.00000000e+000, 2.55336827e-110, 0.00000000e+000],
       [1.00000000e+000, 1.19300865e-159, 0.00000000e+000],
       [1.00000000e+000, 5.95121873e-184, 0.00000000e+000],
       [1.00000000e+000, 5.44247574e-155, 0.00000000e+000],
       [1.00000000e+000, 6.31331724e-130, 2.07619640e-059],
       [1.00000000e+000, 1.03070969e-194, 0.00000000e+000],
       [1.00000000e+000, 1.04074299e-192, 0.00000000e+000],
       [1.00000000e+000, 3.61393704e-159, 0.00000000e+000],
       [1.00000000e+000, 4.98526473e-132, 0.00000000e+000],
       [1.00000000e+000, 7.13528146e-142, 0.00000000e+000],
       [1.00000000e+000, 3.15646316e-160, 1.50967625e-191],
       [1.00000000e+000, 3.16168023e-123, 1.42863754e-279]])

In [207]:
df_iris['cluster'] = clusters_gmm.astype(int)

In [208]:
df_iris.head(10)

   sepal length (cm)  sepal width (cm)  ...  target  cluster
0                5.1               3.5  ...       0        1
1                4.9               3.0  ...       0        1
2                4.7               3.2  ...       0        1
3                4.6               3.1  ...       0        1
4                5.0               3.6  ...       0        1
5                5.4               3.9  ...       0        1
6                4.6               3.4  ...       0        1
7                5.0               3.4  ...       0        1
8                4.4               2.9  ...       0        2
9                4.9               3.1  ...       0        1

[10 rows x 6 columns]

In [209]:
px.scatter(df_iris, x='sepal width (cm)', y='sepal length (cm)', color='cluster')

In [210]:
px.scatter(df_iris, x='petal width (cm)', y='petal length (cm)', color='cluster')

In [211]:
px.scatter(df_iris, x='petal width (cm)', y='sepal length (cm)', color='cluster')

In [212]:
px.scatter(df_iris, x='sepal width (cm)', y='petal length (cm)', color='cluster')